name: CD
on:
  push:
    # paths:
    #   - videohunter-api/**
    #   - videohunter-bot/**
    #   - samconfig.toml
    #   - template.yaml
    #   - Makefile
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
    
      - name: Test
        run: |
          make test
      
      - name: Deploy
        run : | 
          snap remove curl
          apt install -y curl
          make deploy
        env:
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
