name: CI
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.23"
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install staticcheck
        if: matrix.go == '1.23'
        run: make install-staticcheck

      - name: Run linter
        if: matrix.go == '1.23'
        run: make lint

      - name: Run tests app directory
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.go == '1.23'
        with:
          files: ./coverage.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
